version: '3.9'

services:
 postgres:
  image: postgres:15
  container_name: qna_rag_postgresDB
  restart: always
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: pass123
    POSTGRES_DB: qna_rag_db
  ports: 
    - '5432:5432'
  volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: